### ISSUE TITLE
Java 8 JavaScript error

### ISSUE THREAD

**Issue by zamariola** [avatria/ydeploy#2]
I have been experiencing this error:

`ydeploy/core/resources/ant/macros.xml:167: javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 2
    at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)`

The solution for this was:
Insert "load('nashorn:mozilla_compat.js')" before line 168 in macro : ydeploy/core/resources/ant/macros.xml

The final content becomes:
"
`<then>
                    <script language="javascript"><![CDATA[
                        load('nashorn:mozilla_compat.js')                       
                        importClass(java.io.FileInputStream)
                        importClass(java.io.FileOutputStream)
                        importClass(java.util.Properties)
`
Is this right?

**Comment by zmcmahon-avatria** [comment]
Thanks for posting the issue @zamariola! We haven't had a chance to upgrade ydeploy to ensure it works on hybris 6 or Java 8 yet, and it looks like you came across one of the issues.

I think the solution you mention will address the issue assuming you are exclusively using Java 8/nashorn. I do wonder if that will work on Java 7 as well (so we can maintain backwards compatability). I assume the nashorn specific load directive may fail on JDK version < 8, but this is likely simply resolved with a try/catch/ignore.

```
try {
    load("nashorn:mozilla_compat.js");
} catch (e) {
   // ignore the exception - perhaps we are running on Rhino!
}
```

Will test this out sometime soon and commit to the main branch if successful on java 7 and 8.

**Comment by zamariola** [comment]
Hello @zmcmahon-avatria, thank you so much for answering. That try-catch solutions is far way better! I've tried with hybris 5.7 and java 8 and it's working like a charm!

Thank you.

**Comment by zmcmahon-avatria** [comment]
Commited changes. Tested that everything is still working with JDK 7 and 8.
