### ISSUE TITLE
deployrelease failing as extension path gets change automatically

### ISSUE THREAD

**Issue by tripathihsr** [avatria/ydeploy#3]
Hi Zmcmahon,

Thanks for providing the custom build framework.

I was trying to utilize this for my research but it is failing at an specific point.

I am able to successfully execute 'ant build' and 'ant genrelease' but it fails while executing 'any deployrelease'

while troubleshooting i find that some additional paths are added in 'localextension.xml' after 'ant genrelease' but didn't get any clue how to fix it

Please take a look at screnshot

1. This is path of custom extensions which i can in the package 'hybrisServer-Release-0.zip' generated after 'ant genrelease'
![image](https://user-images.githubusercontent.com/28015982/29494669-f7ccd228-85cc-11e7-98f5-5b5918708412.png)

2. snippets after 'ant deployrelease' filure
![image](https://user-images.githubusercontent.com/28015982/29494674-010e596a-85cd-11e7-8acb-4d6491c6186f.png)

Please share some pointers to fix it

**Comment by tripathihsr** [comment]
Please share your comment

**Comment by zmcmahon-avatria** [comment]
Hi @tripathihsr -

It's hard for me to make out the screenshots above as the resolution is poor. A few things would help me understand better.

1. What version of hybris are you using?
2. Can you post the full output for the command that is failing as plain text?
3. You mention that new localextensions.xml entries are added after genrelease. ydeploy doesn't modify this file, but the hybris build process may. I'm wondering if the paths are setup correctly as hybris may generate new config files from 'templates' if it doesn't see the files in the config location. Check to make sure you have the localextensions.xml and other files in the 'config' directory and that 'ydeploy' exists in the config directory as described here: https://github.com/avatria/ydeploy#checking-ydeploy-into-source-control

Thanks,
Zach

**Comment by tripathihsr** [comment]
uff..i dont know why couldn't see your reply, sorry 

Please find response below..

1. Hybris-commmerce-6.3
2. 
![image](https://user-images.githubusercontent.com/28015982/30243205-79157b5a-95c2-11e7-9abb-ab1dc5632b72.png)
..

deployrelease:
     [echo] Initializing ydeploy
     [echo] ydeploy yenv:
     [echo] ydeploy yserverid:
     [echo] ydeploy yreleaseid: 0

-init:

server-stop:
     [exec] Stopping hybrisPlatform on Tomcat...
     [exec] Waiting for hybrisPlatform on Tomcat to exit...
     [exec] Stopped hybrisPlatform on Tomcat.
    [mkdir] Created dir: /app/deploy/releases/0
     [copy] Copying 31 files to /app/deploy/releases/0
    [unzip] Expanding: /app/deploy/releases/0/hybrisServer-AllExtensions.zip into /app/deploy/releases/0
    [unzip] Expanding: /app/deploy/releases/0/hybrisServer-Config.zip into /app/deploy/releases/0
    [unzip] Expanding: /app/deploy/releases/0/hybrisServer-Licence.zip into /app/deploy/releases/0
    [unzip] Expanding: /app/deploy/releases/0/hybrisServer-Platform.zip into /app/deploy/releases/0
  [symlink] Removing symlink: /app/deploy/current
     [exec] Buildfile: /app/deploy/releases/0/hybris/bin/platform/build.xml
     [exec]      [echo] deploylocalproperties starting...
     [exec]      [echo] ydeploy yenv:
     [exec]      [echo] ydeploy yserverid:
     [exec] [propertyfile] Updating property file: /app/deploy/releases/0/hybris/temp/hybris/ydeploy/local.properties
     [exec]      [copy] Copying 1 file to /app/deploy/releases/0/hybris/config
     [exec]      [echo] deploylocalproperties complete
     [exec]     [mkdir] Created dir: /app/deploy/releases/0/hybris/roles
     [exec]
     [exec] BUILD FAILED
     [exec] /app/deploy/releases/0/hybris/bin/platform/build.xml:16: The following error occurred while executing this line:[ysetplatformproperties] Error while evaluating file '/app/deploy/releases/0/hybris/config/localextensions.xml'. ExtensionInfo file '/app/deploy/releases/0/hybris/bin/../../../../../custom/teststorefulfilmentprocess/extensioninfo.xml' could not be found! Check the extensions paths specified in your '/app/deploy/releases/0/hybris/config/localextensions.xml' !
     [exec]
     [exec] [ysetplatformproperties] java.lang.RuntimeException: Error while evaluating file '/app/deploy/releases/0/hybris/config/localextensions.xml'. ExtensionInfo file '/app/deploy/releases/0/hybris/bin/../../../../../custom/teststorefulfilmentprocess/extensioninfo.xml' could not be found! Check the extensions paths specified in your '/app/deploy/releases/0/hybris/config/localextensions.xml' !
     [exec] /app/deploy/releases/0/hybris/bin/platform/resources/ant/antmacros.xml:155: java.lang.RuntimeException: Error while evaluating file '/app/deploy/releases/0/hybris/config/localextensions.xml'. ExtensionInfo file '/app/deploy/releases/0/hybris/bin/../../../../../custom/teststorefulfilmentprocess/extensioninfo.xml' could not be found! Check the extensions paths specified in your '/app/deploy/releases/0/hybris/config/localextensions.xml' !
     [exec] [ysetplatformproperties]    at de.hybris.bootstrap.config.PlatformConfig.readConfiguredExtensionsFromXMLFile(PlatformConfig.java:1219)
     [exec]     at de.hybris.bootstrap.config.PlatformConfig.readConfiguredExtensionsFromXMLFile(PlatformConfig.java:1219)
     [exec] [ysetplatformproperties]    at de.hybris.bootstrap.config.PlatformConfig.collectConfiguredExtensionsFromXMLConfig(PlatformConfig.java:1041)
     [exec]     at de.hybris.bootstrap.config.PlatformConfig.collectConfiguredExtensionsFromXMLConfig(PlatformConfig.java:1041)
     [exec] [ysetplatformproperties]    at de.hybris.bootstrap.config.PlatformConfig.collectConfiguredExtensions(PlatformConfig.java:953)       at de.hybris.bootstrap.config.PlatformConfig.collectConfiguredExtensions(PlatformConfig.java:953)
     [exec]
     [exec]     at de.hybris.bootstrap.config.PlatformConfig.<init>(PlatformConfig.java:139)[ysetplatformproperties]    at de.hybris.bootstrap.config.PlatformConfig.<init>(PlatformConfig.java:139)
     [exec]
     [exec]     at de.hybris.bootstrap.config.PlatformConfig.getInstance(PlatformConfig.java:128)[ysetplatformproperties]       at de.hybris.bootstrap.config.PlatformConfig.getInstance(PlatformConfig.java:128)
============================

![image](https://user-images.githubusercontent.com/28015982/30243230-e370f90c-95c2-11e7-827f-ba1dd32ba97a.png)

3. yes i have config directory at <ydeploy>/config
but additional path are getting added as highlighted in yellow in above screenshot

**Comment by tripathihsr** [comment]
One more clarification from below

# Where hybris platform zip releases are stored
yd.hybris.platform.releases.dir=/opt/build/hybris/releases

# The hybris platform zip file to use for 'build' and 'genrelease' targets. 
# Must exist in the ${yd.hybris.platform.releases.dir} location
yd.hybris.platform.release.file=hybris-commerce-suite-5.4.0.1.min.zip
**## (Do wee need to copy here hybris installer or package which was generate after "ant genrelease"?)**
# Location at which the 'deployrelease' and server related targets will operate.
yd.hybris.platform.deploy.dir=/opt/hybriscs

**Comment by tripathihsr** [comment]
Hi Zmcmahon, do you think you can help here?

Regards!

**Comment by zmcmahon-avatria** [comment]
@tripathihsr -

1. What are the contents of the localextensions.xml before running the build (i.e. before deploy)? Can you please post the full contents before & after for comparison?
2. The following reference in the localextensions.xml "/app/deploy/releases/0/hybris/bin/../../../../../custom/teststorefulfilmentprocess/extensioninfo.xml" will resolve to /app/deploy/custom/teststorefulfilmentprocess/extensioninfo.xml. I assume that file/path doesn't exist, correct? What is the actual path of the teststorefulfilmentprocess module under the "deploy/releases/0" directory? Typically it would be located under deploy/releases/0/hybris/custom/teststorefulfilmentprocess. If not, you would have to configure the yd.hybris.custom.ext.dir property to point the custom location.
3. What OS are you using?
4. Can you confirm that after the failure, symbolic links exist pointing /app/deploy/current => /app/deploy/releases/0?
5. Please post any customizations made to any of the yd.* properties files via ydeploy.properties, core.properties, or similar config files.
6. What is the structure and relative relationships between your hybris bin, config, custom, and ydeploy directories? Typically it would be something like hybris/bin, hybris/config, hybris/custom, and hybris/ydeploy, respectively.

As mentioned previously, ydeploy does not modify the localextensions.xml file, but the core hybris build process may. You may want to try just modifying the localextensions.xml in the expanded releases/0 directory to point to the correct path, and then invoke the hybris build process directly just to make sure everything is working and building. To me it sounds like some step is failing quietly (such as the symbolic link creation), the ydeploy configurations are incorrect based upon the actual directory layout you are using, or perhaps there is a fully qualified path somewhere in your configuration (possibly localextensions.xml) during build time. Will need more details regarding your configuration & layout to know.

**Comment by tripathihsr** [comment]
1.	What are the contents of the localextensions.xml before running the build (i.e. before deploy)? Can you please post the full contents before & after for comparison?
In code repository:
	<?xml version="1.0" encoding="UTF-8"?>
	<hybrisconfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resources/schemas/extensions.xsd">
        <extensions>
                

                <path dir="${HYBRIS_BIN_DIR}" />
                <extension name='teststorecore'/>
                <extension name='teststoreinitialdata'/>
                <extension name='teststorefacades'/>
                <extension name='teststorestorefront'/>
                <extension name='teststorecockpits'/>
                <extension name='teststorefulfilmentprocess'/>
                <extension name='teststoretest'/>

                

        </extensions>

After ‘ant build’ (no change)
	<?xml version="1.0" encoding="UTF-8"?>
	<hybrisconfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resources/schemas/extensions.xsd">
        <extensions>
                

                <path dir="${HYBRIS_BIN_DIR}" />
                <extension name='teststorecore'/>
                <extension name='teststoreinitialdata'/>
                <extension name='teststorefacades'/>
                <extension name='teststorestorefront'/>
                <extension name='teststorecockpits'/>
                <extension name='teststorefulfilmentprocess'/>
                <extension name='teststoretest'/>

                

        </extensions>
After ‘ant genrelease’
<?xml version='1.0' encoding='UTF-8'?>

<hybrisconfig xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='resources/schemas/extensions.xsd'>

        <extensions>
                
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/voucher'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/promotions'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/customerreview'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-cockpit/cockpit'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-platform-optional/springintegrationlibs'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/solrfacetsearch'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/basecommerce'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/payment'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-cockpit/admincockpit'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-platform-optional/virtualjdbc'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-content/cms2'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/commerceservices'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/commercefacades'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-content/cms2lib'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-cockpit/reportcockpit'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/ticketsystem'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-channel/cscockpit'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-content/productcockpit'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-content/cmscockpit'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-commerce/solrserver'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-accelerator/acceleratorservices'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-accelerator/acceleratorcms'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-accelerator/acceleratorfacades'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-accelerator/acceleratorstorefrontcommons'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-data/apparelstore'/>
                <extension dir='${HYBRIS_BIN_DIR}/ext-data/electronicsstore'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststorefulfilmentprocess'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststorecockpits'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststorecore'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststorefacades'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststoretest'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststorestorefront'/>
                <extension dir='${HYBRIS_BIN_DIR}/../../../../../bin/custom/teststoreinitialdata'/>
        </extensions>

</hybrisconfig>
This step creates issue by adding ‘/../../../../../’ in original path 

2.	The following reference in the localextensions.xml "/app/deploy/releases/0/hybris/bin/../../../../../custom/teststorefulfilmentprocess/extensioninfo.xml" will resolve to /app/deploy/custom/teststorefulfilmentprocess/extensioninfo.xml. I assume that file/path doesn't exist, correct? What is the actual path of the teststorefulfilmentprocess module under the "deploy/releases/0" directory? Typically it would be located under deploy/releases/0/hybris/custom/teststorefulfilmentprocess. If not, you would have to configure the yd.hybris.custom.ext.dir property to point the custom location.
[tripathihsr]- this is the main issue , reference in ‘localextension’ are getting changed to another path with doesn’t exist (example, "/app/deploy/releases/0/hybris/bin/../../../../../custom, ) original path is "/app/deploy/releases/0/hybris/bin/custom
3.	What OS are you using?
[tripathihsr]- I tried both in centos7 & RHEL7
4.	Can you confirm that after the failure, symbolic links exist pointing /app/deploy/current => /app/deploy/releases/0?
[tripathihsr]- Yes, it does
 

5.	Please post any customizations made to any of the yd.* properties files via ydeploy.properties, core.properties, or similar config files.
[tripathihsr]-no customization in core,properties, path change in ydeploy.properties ( even tried with the default config but faced similar issue)
yd.hybris.custom.ext.dir=${yd.root.dir}/../bin/custom
yd.hybris.custom.config.dir=${yd.root.dir}/../config
# hybris build tasks to perform when the ydeploy 'build' target is invoked
yd.tasks.build.hybrisbuildtargets=customize all
# hybris build tasks to perform when the ydeploy 'genrelease' target is invoked
yd.tasks.genrelease.hybrisbuildtargets=customize all production
yd.tasks.genrelease.output.dir=${yd.temp.dir}/genreleaseyd.tasks.genrelease.releasefileprefix=hybrisServer-Release
# hybris build tasks to perform when the ydeploy 'deployrelease' target is invoked on the target server
yd.tasks.deployrelease.hybrisbuildtargets=all

6.	What is the structure and relative relationships between your hybris bin, config, custom, and ydeploy directories? Typically it would be something like hybris/bin, hybris/config, hybris/custom, and hybris/ydeploy, respectively.
[tripathihsr]-
1st I tried default
	hybris-repo
		/config
			/localextensions.xml
			[ . . . ]
		/custom
			/custext1
			/custext2
			[ . . . ]
	/ydeploy

Later I changed to below
	hybris-repo
                  /hybris 
                         /bin
                              /custom
                                     /custext1
                                     /…….  
   			/config
			     /localextensions.xml
			      [ . . . ]
	
			/ydeploy

Regards!

**Comment by tripathihsr** [comment]
some text messages are distorted
see reference for #4
![image](https://user-images.githubusercontent.com/28015982/30375313-bb527bd6-98a5-11e7-940e-e6b92dc8d2e2.png)

**Comment by zmcmahon-avatria** [comment]
@tripathihsr -

Thanks for providing all the info.

I had a chance to test your setup using 6.3 on windows & linux today, and it does look like you've run into an issue for linux setups caused by changes in the hybris 6.3 'production' build task. Specifically, they are now regenerating the config/localextensions.xml file by default (can disable with production.generate.extensionsxml=false property), but the paths are not being generated correctly when symbolic links are used for the bin/custom directory.

I've made some updates in the branch below which seemed to resolve the issue for me. Can you integrate these changes into your setup and retry?
https://github.com/avatria/ydeploy/commit/37e26f0d9ea3e3aa80778bebe86f1658439afba1

You will need to run both 'build' and 'genrelease' again in a clean setup (i.e. delete anything under the ydeploy/temp directory) before running 'deployrelease'. 

If all works well on your end, I will merge these changes into the master branch.

Thanks,
Zach

**Comment by tripathihsr** [comment]
Hi Zach, glad to confirm that it is working fine.
Thank you so much for quick assistance, have a great time!
Regards!

**Comment by zmcmahon-avatria** [comment]
@tripathihsr - Glad to hear! Thanks again for reporting the issue and working through.

**Comment by zmcmahon-avatria** [comment]
Merged to master. Cut new release [v0.1.4](https://github.com/avatria/ydeploy/releases/tag/ydeploy-v0.1.4).
