### ISSUE TITLE
ydeploy is not able to pick hybris server

### ISSUE THREAD

**Issue by amitmahala** [avatria/ydeploy#4]
HI Zmcmahon,
![serverfail](https://user-images.githubusercontent.com/31985910/30586663-565c4ce0-9d4e-11e7-9651-ee174a66b89f.PNG)
My Hybris server is up & running  which I have stared from platform directory (local system) using hybrisserver.bat
Should be there any config change so that ** ant deployrelease** command will pick location for running hybris instance ?

Below is the error I am getting when tried deploying using ** ant deployrelease** command.

D:\ydep\YDEPLO~1\current\hybris\bin\platform\tomcat\bin\..\conf\wrapper.conf
[exec] The hybris Server 6.0.0.1 service is not installed - The specified service does not exist as an installed service. (0x424)

Thanks

**Comment by zmcmahon-avatria** [comment]
Hi @amitmahala - 

From what I see, my guess is the problem isn't with ydeploy not being able to find the correct deploy location, but rather that ydeploy tries to startup the instances as a service on Windows. You can install the hybris tomcat instance as a service on Windows by running the hybris/bin/platform/tomcat/bin/InstallTomcatService.bat script from the location which hybris is installed. For ydeploy, this will be your deploy location (e.g. deploy/current/hybris/...).

Right now ydeploy does not do this automatically on Windows and assumes the Windows service already has been configured. On linux systems, a service does not need to be installed, so it shouldn't be an issue.

If you would like for the service to be installed automatically as part of the deploy process, you should pretty easily be able to invoke the install service script from deployrelease target prior to the server startup command being issued.

**Comment by zmcmahon-avatria** [comment]
Closing due to no response.
